model_path: ./coco.rknn
batch_size: 1
dtype: uint8
img_size:
- 384
- 640
input_name: input_0
output_names: 
- reg0
- reg1
- reg2
- obj_conf0
- obj_conf1
- obj_conf2
- cls_conf0
- cls_conf1
- cls_conf2
names:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports ball
- kite
- baseball bat
- baseball glove
- skateboard
- surfboard
- tennis racket
- bottle
- wine glass
- cup
- fork
- knife
- spoon
- bowl
- banana
- apple
- sandwich
- orange
- broccoli
- carrot
- hot dog
- pizza
- donut
- cake
- chair
- couch
- potted plant
- bed
- dining table
- toilet
- tv
- laptop
- mouse
- remote
- keyboard
- cell phone
- microwave
- oven
- toaster
- sink
- refrigerator
- book
- clock
- vase
- scissors
- teddy bear
- hair drier
- toothbrush
obj_conf_enabled: true
normalize: false

kwargs:
  conf_threshold: 0.25
  nms_threshold: 0.5
  core: all
  version: edgeyolo
  show_info: true
